FROM webdevops/php:latest
ENV TIMEZONE Asia/Bangkok
# set timezone
RUN cp /usr/share/zoneinfo/${TIMEZONE} /etc/localtime && echo "${TIMEZONE}" >  /etc/timezone
ENV PHP_UPLOAD_MAX_FILESIZE: 500m
ENV PHP_POST_MAX_SIZE: 500m

EXPOSE 9000
CMD ["supervisord"]